### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by swarup-cloud** [sanki4489/Jest-test-specs#9]
@sanki4489 
I have decide to add few things to the repository :-
1. Add pagination for vue files
2. Add test case for Pagination

# Details 
1. its a contribution for vue and nuxt.js
2. Lets add more files and test suite for more vue and nuxt.

# Status
implemented and directly pushed to main branch.

**Comment by sanki4489** [comment]
Thanks for your contribution.

**Comment by swarup-cloud** [comment]
Done.
